// Code generated by tygo. DO NOT EDIT.

//////////
// source: authors.sql.go

export interface CreateAuthorParams {
  Name: string;
  Bio: null | string;
}
export interface UpdateAuthorParams {
  Name: string;
  Bio: null | string;
  ID: number /* int64 */;
}

//////////
// source: db.go

export type DBTX = any;
export interface Queries {
}

//////////
// source: models.go

export interface Author {
  ID: number /* int64 */;
  Name: string;
  Bio: null | string;
}
