name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Required for git describe to work properly

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.0'

    - name: Install dependencies
      run: |
        go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
        go install github.com/a-h/templ/cmd/templ@latest
        go install gotest.tools/gotestsum@latest

    - name: Run audit
      run: make audit
      
    - name: Build
      run: make build
      
    - name: Test
      run: make test
