name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: |
          go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
          go install github.com/a-h/templ/cmd/templ@latest
          go install gotest.tools/gotestsum@latest

      - name: Run audit
        run: make audit
      
      - name: Run tests
        run: make test

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build binaries
        run: VERSION=${{ steps.get_version.outputs.VERSION }} make build-all

      - name: Publish to Go proxy
        run: GOPROXY=proxy.golang.org go list -m github.com/gitkumi/snowflake@${{ steps.get_version.outputs.VERSION }} 
